### ISSUE TITLE
Wrong time range

### ISSUE THREAD

**Issue by harshika18** [wikimedia/WikiContrib#149] opened 2020-03-19 10:52 UTC
When we specify the time range using filter like "Last 6 months" it should generate the graph by taking data from previous 6 months. But it generate a random time period from November 2020 to February 2020 which is actually not even a possible time range. May be it will be problematic when we need to change the year to see data of last few months.
![wiki1](https://user-images.githubusercontent.com/44746365/77059910-b9055c00-69fd-11ea-85b3-2928e80b7509.png)

**Comment by harshika18** [comment] 2020-03-19 10:53
I am an outreachy aspirant, I would like to work on this issue. Can I?

**Comment by eeshadutta** [comment] 2020-03-19 13:48
Hey @harshika18 I think this issue is the same as the one in #98 (also #123 ). Issue #102  is also related to this.

**Comment by srish** [comment] 2020-03-21 05:49
(thanks @harshika18 for filing this issue. But, it seems like a duplicate of existing ones as @eeshadutta mentioned)

**Closed by srish** 2020-03-21 05:49 UTC
