### ISSUE TITLE
Check if the input fields are valid or linked to the same person

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#23] opened 2019-08-26 21:22 UTC
I'm not sure if this is feasible, but ideally, we check if the full name, Gerrit and Phabricator username entered by a user are valid and if or not they are linked to the same person. If not, then we don't proceed.

**Comment by Jain-Aditya** [comment] 2019-10-04 05:44
@srish I think this is a major issue and an important one. I think this could be addressed by checking if the Full name returned by the Gerrit and Phabricator API called for their respective usernames is same as entered by the User in the search form. If it is not so we could display an error message.

**Comment by rammanoj** [comment] 2019-10-15 02:32
@srish is there any way to check it out ?? How to validate if the phabricator and gerrit account username's entered are linked to the same person ? Is there any API present to perform it ?

**Comment by srish** [comment] 2019-10-15 20:30
@rammanoj Good question! I'm not aware of any :-/ I guess this would require a bit of research and ask around folks at Wikimedia :)

**Comment by rammanoj** [comment] 2019-10-16 10:56
@srish can I ask about it here(https://discourse-mediawiki.wmflabs.org/) ?

**Comment by Jain-Aditya** [comment] 2019-10-16 15:53
@rammanoj @srish Validating that all the fields belong to the same users might be a tough task. But, still we could check if the fields entered by a user are even correct or not, which would be a major improvement to the present search interface.
For instance, If I search for a username(xyz) that don't even exists then we will not proceed and display an error message.

**Comment by srish** [comment] 2019-10-16 23:18
@Jain-Aditya Thanks for the idea, I like it a lot! :) 
@rammanoj I think if anyone else who might know if there are any APIs would be folks on the IRC channel: #wikimedia-releng. You could get in touch with them. In any case, I'm liking @Jain-Aditya's idea a lot. I think we should definitely do the checks.

**Comment by NdibeRaymond** [comment] 2020-03-08 02:15
Ok. This kinda looks interesting. Can I work on it @srish?

**Comment by NdibeRaymond** [comment] 2020-03-12 21:04
Hello @srish , I would like to work on this feature implementation

**Comment by srish** [comment] 2020-03-13 23:48
@NdibeRaymond If you can do some research on this, that'd be great!

**Comment by eeshadutta** [comment] 2020-03-19 03:18
@srish when a wrong username for Gerrit or Phabricator is provided (one that doesn't exist), the activity page still loads. Is this the expected behavior?

**Comment by NdibeRaymond** [comment] 2020-03-19 04:25
@srish there seems to be no APIs that can handle this edge case. Even if we retrieve the full names from gerrit and Phabricator, there is no guarantee that the user will use the same fullname in the same order.
One thing that can be done here is fuzzy matching, where the result of checking whether the usernames belong to the same user will return a percentage value instead of direct true or false value. We can then decide what reasonable percentage means true.
This approach is not perfect but it will eliminate situations where the full names are completely different.
Then another thing we can do is what @Jain-Aditya suggested, introducing a measure of validation to handle names that doesn't exist.
With your approval, I can begin working on this

**Comment by srish** [comment] 2020-03-21 05:24
@NdibeRaymond Hmm! Can you give me an example for the percentage approach? I don't think I fully understand this.

**Comment by NdibeRaymond** [comment] 2020-03-21 09:32
Ok. Here is how it can be done.
 * First, a user submits fullname, 
   garrit_username and Phab_username.
 * We check if there is a user with the 
   submitted usernames for gerrit and phab 
   and if so, return the users fullname from 
   both gerrit and phab. If the usernames 
   doesn't exist, we can't take action (maybe 
    return error message)
 * When the user full names are returned 
    from gerrit and phab, we compare both 
    of them to the fullname initially 
    submitted by the user.

Since a fullname is not something that is changes alot (maybe the order might change or middle name excluded, but it should remain very similar to the submitted fullname), we can be able to use fuzzy matching tell with percentage accuracy, if the usernames match or not. For example a  value of 70-100% will comparing say gerrit_fullname and submitted fullname can be taken to mean that we are dealing with the same user, while something lower than 40% can be seen as unacceptable. 
Also, we can also decide to compare gerrit_fullname directly to phab_fullname (Incase we are uncertain if the submitter knows the fullname of the user before hand), it should yield similar result.
We can also do a combination of both approach

**Comment by NdibeRaymond** [comment] 2020-03-29 10:21
Hello @rammanoj  and @srish , I proposed a way to handle this issue here #159 . Is it possible to review this approach and give feedback?

**Comment by srish** [comment] 2020-04-03 06:24
@NdibeRaymond left a note here https://github.com/wikimedia/WikiContrib/pull/159#issuecomment-608252457

**Comment by NdibeRaymond** [comment] 2020-06-16 18:27
@srish , I believe since this issue has been fixed, we should close it. Any thoughts?

**Closed** 2020-06-17 23:42 UTC
Labels: Priority: Low, enhancement
