### ISSUE TITLE
No check for non-existent username input

### ISSUE THREAD

**Issue by eeshadutta** [wikimedia/WikiContrib#144] opened 2020-03-18 06:09 UTC
The activity page still loads when an incorrect/non-existent username is provided for Gerrit/Phabricator fields on the homepage. 

If there are Gerrit/Phabricator APIs that allow us to check if an account with a specific username exists or not, this issue could be addressed.

**Comment by NdibeRaymond** [comment] 2020-03-18 08:29
I am currently researching this at #23 .
That being said, I believe the purpose of the tool is for a user to be able to access other people's contributions, therefore authentication before viewing contributions doesn't apply here, right @srish ?

**Comment by eeshadutta** [comment] 2020-03-18 15:33
Since, this is more of a Research issue, hope its ok if I look it up as well, @srish

**Comment by srish** [comment] 2020-03-19 01:46
@eeshadutta @NdibeRaymond That's correct! Authentication would add complexity to this project and not needed. Feel free to research/ add any findings in the issue (23) linked above.

**Comment by eeshadutta** [comment] 2020-03-19 03:18
@srish  when a wrong username for Gerrit or Phabricator is provided (one that doesn't exist), the activity page still loads. Is this the expected behavior?

**Comment by srish** [comment] 2020-03-21 04:48
@eeshadutta That's a great question, and it is not the expected behavior. But, I am not sure if there are Gerrit/Phabricator APIs that allow us to check if an account with a specific username exists or not. Still, this is a separate issue and not related to authentication, and we don't need the later.

**Comment by eeshadutta** [comment] 2020-03-21 06:43
@srish should I file an issue regarding this ' when a wrong username for Gerrit or Phabricator is provided (one that doesn't exist), the activity page still loads'? And we can explore it separately?

**Comment by srish** [comment] 2020-03-24 02:34
@eeshadutta You can modify this task (title+desc) itself accordingly.

**Comment by eeshadutta** [comment] 2020-03-24 18:08
@srish made the necessary changes

**Comment by NdibeRaymond** [comment] 2020-03-26 22:12
@srish are we allowed to work on issues already assigned to another person? because this issue is part of what was detailed in #23 and has been assigned to me. I've also submitted a PR detailing my findings and waiting for your approval to go on and implement it

**Comment by srish** [comment] 2020-03-27 01:32
@NdibeRaymond I haven't assigned this issue to anyone yet! But, I do think that issue 23 is more about researching whether or not the input fields provided are linked to the same person or not. While, this issue is about checking whether or not username provided for Gerrit or Phabricator exists or not. Hope this makes sense!

**Comment by NdibeRaymond** [comment] 2020-03-27 01:38
@srish ?
![IMG_20200327_023718](https://user-images.githubusercontent.com/40905613/77712445-14be7f00-6fd4-11ea-850f-ee16cacf230a.jpg)
![IMG_20200327_023757](https://user-images.githubusercontent.com/40905613/77712447-16884280-6fd4-11ea-9835-903bed870308.jpg)

**Comment by srish** [comment] 2020-03-27 01:43
@NdibeRaymond Oops! My bad.. I'm sorry. I confused 23 with another issue :-/ 

(closing this as a possible duplicate)

**Closed by srish** 2020-03-27 01:43 UTC
