### ISSUE TITLE
Site is breaking!! 404 not found

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#166] opened 2020-03-24 11:57 UTC
![IMG_20200324_124314](https://user-images.githubusercontent.com/40905613/77423077-e1f76980-6dce-11ea-9bbb-5211853ea546.jpg)

It's possible this is as a result of recent merges. If it's not, then I'd love to look into it.
Can someone else please confirm this as well @srish ?

**Comment by srish** [comment] 2020-03-24 22:47
@NdibeRaymond thanks for reporting this! @rammanoj The site is up again! I didn't do anything, except that I made some test commits directly into master to investigate a recent PR that I had a doubt on. I think this probably triggered travis and the site is back up again now.

Though, we are getting the same travis error now as with some previous commits: https://github.com/wikimedia/WikiContrib/commit/9593284ff6b52ad5e667c3cf6ef9d9e8eb92e53e (see below), I'm wondering if this is an issue with travis setup itself? Because, none of the recent changes caused this, I checked.

```
0.01s$ openssl aes-256-cbc -K $encrypted_382dfcbe1831_key -iv $encrypted_382dfcbe1831_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
iv undefined
The command "openssl aes-256-cbc -K $encrypted_382dfcbe1831_key -iv $encrypted_382dfcbe1831_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by srish** [comment] 2020-03-24 23:35
I spoke too soon I think, I noticed the site going down again quite late. I confirm that the changes in https://github.com/wikimedia/WikiContrib/issues/122 are causing a 404 though they are working fine for me locally so I've reverted them for now: 
https://github.com/wikimedia/WikiContrib/commit/952d888d8716ead57fda53e440184076dc8eeaec

(if anyone wants to fix that, you can modify the title and desc accordingly) 

@rammanoj feel free to ignore my earlier comment, travis isn't causing the issue.

**Comment by NdibeRaymond** [comment] 2020-03-25 00:13
I did a bit of research on this and found that this is a problem with the react-loable package. it is no longer maintained and doesn't work well with webpack version 4+
I can reimplement the code splitting with the official react recommended way

**Comment by muskangupta-iitr** [comment] 2020-03-27 03:41
@srish I would like to give it a chance before it is assigned to someone else. I request you to please let me try fixing it once. :)

**Comment by muskangupta-iitr** [comment] 2020-03-29 05:29
> I did a bit of research on this and found that this is a problem with the react-loadable package. it is no longer maintained and doesn't work well with webpack version 4+
> I can reimplement the code splitting with the official react recommended way, but then
> since this looks like a potential grey area (the changes have been reverted so implementing it is like implementing an issue that was assigned to somebody else), should I wait for her to try reimplementing the code splitting correctly or should I go ahead @srish ?

@NdibeRaymond Can you help me reproducing the error your are getting? Also, just want to mention I implemented the code using official react docs only but yes `react-loadable` is no longer maintained by anyone instead of that `React.lazy()` is being used. I will update that change.

**Comment by rammanoj** [comment] 2020-03-29 08:48
Hello all,
This is not any problem with the app. If any PR got merged or any commit made in the app, the travis-ci pulls the changes from github and updates the server with the latest commits. It restarts the server. It takes some time for the server to restart. So, whoever tries to make a request to this site during this time, the site may show you a 404 response. If travis CI fails with any error. The service will be stopped and will not be restarted. So, we need to manually restart the service then.

Can anyone tell me if anytime when the app showed you 404 response. Did anyone make any changes somewhere to fix it ?

**Comment by NdibeRaymond** [comment] 2020-03-29 09:33
This happened after a certain PR was merged. And it shouldn't have taken more than a day to build if it was was just build running. The only changes made after the issue is to reverse the PR

**Comment by srish** [comment] 2020-03-30 06:39
@rammanoj I reversed the PR in https://github.com/wikimedia/WikiContrib/commit/952d888d8716ead57fda53e440184076dc8eeaec after we got the 404 error with the code splitting changes (in the lieu ended up making some test commits on March 24th https://github.com/wikimedia/WikiContrib/commits/master). The error was showing for a really long time, so my sense was that it has something to do with the code splitting changes.

**Closed** 2020-04-13 12:21 UTC
