### ISSUE TITLE
Wrong contribution chart

### ISSUE THREAD

**Issue by harshika18** [wikimedia/WikiContrib#178] opened 2020-03-28 14:11 UTC
When we look at december, it contain contributions but if we select 3 month time range it shows zero contribution.
![Screenshot from 2020-03-28 19-34-43](https://user-images.githubusercontent.com/44746365/77824920-fcfa0e80-712b-11ea-99a5-aacd1d34d95d.png)
![Screenshot from 2020-03-28 19-35-58](https://user-images.githubusercontent.com/44746365/77824922-fec3d200-712b-11ea-9fcf-05e048951129.png)

**Comment by srish** [comment] 2020-03-30 06:26
@harshika18 Thanks for filing this! I am closing this issue as a possible duplicate of some of the existing issues we have around incorrect time range unless you feel strongly that it is not the case.

**Closed by srish** 2020-03-30 06:26 UTC
